### ISSUE TITLE
Smaller work chunks

### ISSUE THREAD

**Issue by andrin-n-dream** [FoldingAtHome/fah-nacl-client#78]
It seems that the average job an embed nacl client executes takes about 1 hour.
Would it be possible to request jobs that last only 10 minutes?

**Comment by jcoffland** [comment]
This is not a function of the client in the F@H system.  The project determines how long it will run on an average machine.  We have to strike a balance between keeping WUs relatively short and not overloading our servers with too many requests.  If we make WUs too short then the whole thing becomes too inefficient because the cost of uploading and downloading data outweighs the benefit of the parallelism created by running F@H on multiple clients.
